### ISSUE TITLE
`deepPed_demo` makes matlab crushed

### ISSUE THREAD

**Issue by panfengli** [DenisTome/DeepPed#2]
I work fine with `rcnn_demo` but after I download all the codes and data from yours, running `deepPed_demo` makes matlab crushed saying "Matlab has encountered an internal problem and needs to close". My platform is Ubuntu 15.04 & Caffe v0.999 & Matlab2015b.

The errors are shown as follows: 

```
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 7:7: Message type "caffe.NetParameter" has no field named "layer".
F0518 12:21:06.165700  6911 upgrade_proto.cpp:571] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model-defs/alexnet_deploy_fc7_CAFFE.prototxt
*** Check failure stack trace: ***
```

**Comment by panfengli** [comment]
`rcnn_model = rcnn_load_model(rcnn_model_file, use_gpu);`
This command goes wrong. It seems like the model used here is different with the model in `rcnn_demo`

This is the `rcnn_model` I saw in `rcnn_demo`
`cnn`
`cache_name`
`detectors`
`classes`
`training_opts`
`SVs`

This is the `rcnn_model` I saw in `deepPed.demo`
`cnn`
`cache_name`
`detectors`

**Comment by spongezhang** [comment]
It seems that the author put the wrong version of the prototxt file. Caffe v0.999 can only read the old one. The solution is to get an old version of the prototxt file of the AlexNet, delete fc8 layer and change the input dimension to 256. You can find all the information from the prototxt file provided by the author.

**Comment by SuperLee0** [comment]
@spongezhang I use caffe-rc2, and get the same problem, is it the same reason causes? or how can i do to solve it. thanks

**Comment by spongezhang** [comment]
@SuperLee0 I'm not very familar with the rc2 version. The easiest way to check this is to check the model files in $CAFFE_ROOT/models/bvlc_alexnet directory. If the model file is the old version, you should try my solution. I think it should work.

**Comment by cstsdf** [comment]
I have the same problem. Is anyone has the solution?

**Comment by spongezhang** [comment]
@SuperLee0 @cstsdf see #3 . I have added the workable model file.

**Comment by rectoyon** [comment]
@spongezhang I get the same error complaining about the text format at the beginning of this chain with the model committed to the master branch. Is your model different from what is committed to the master branch?

**Comment by spongezhang** [comment]
@rectoyon The model is the same. The format of the model files are different. You should make it working using my prototxt file which based on the old caffe version.

**Comment by rectoyon** [comment]
@spongezhang thanks. I had to use the same model in the rcnn/model-defs directory as well as the DeepPed directory then it worked.

**Comment by HarshaVardhanP** [comment]
@rectoyon @spongezhang 

Had tough time to make caffe.v.0.999 working.

Finally, RCNN Demo is working on my machine on GPU (2GB 960M). 
Thanks for your comments. I changed files as you suggested to make DeepPed work. But not able to run it using GPU (insufficient memory error). 

Currently working on CPU mode. Thanks

GPU Error:
I0913 17:58:07.559538 29365 net.cpp:174] Network initialization done.
I0913 17:58:07.559542 29365 net.cpp:175] Memory required for Data 1446243328
F0913 17:58:21.882158 29365 syncedmem.cpp:47] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
**\* Check failure stack trace: ***
Killed

**Comment by DenisTome** [comment]
If you don't have enough memory you can always reduce the batch size. It's possible to change this parameter in the prototxt file which contains the definition of the architecture.
